import Head from "next/head";
import Link from "next/link";
import { Fragment } from "react";
import { IoLogoFacebook, IoLogoTwitter } from "react-icons/io";
import { Navbar } from "../navbar";

type LayoutProps = {
  children: React.ReactElement;
};

const Layout = ({ children }: LayoutProps): React.ReactElement => {
  return (
    <Fragment>
      <Head>
        <title>Zemoga - UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="font-sans">{children}</main>

      <footer className="p-4">
        <div className="w-full border-t-2 border-dashed border-black my-4" />
        <div className="flex">
          <div className="flex flex-grow flex-col gap-y-4 md:flex-row md:gap-x-4 md:items-center">
            <Link href="#">
              <a>Terms and Conditions</a>
            </Link>
            <Link href="#">
              <a>Privacy Poilcy</a>
            </Link>
            <Link href="#">
              <a>Contact Us</a>
            </Link>
          </div>
          <div className="flex flex-col justify-end md:flex-row md:gap-x-4 md:items-center">
            <p>Follow us</p>
            <div className="flex justify-between items-center text-3xl md:gap-x-2">
              <Link href="#">
                <a aria-label="facebook">
                  <IoLogoFacebook />
                </a>
              </Link>
              <Link href="#">
                <a aria-label="twitter">
                  <IoLogoTwitter />
                </a>
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </Fragment>
  );
};

export { Layout };
